package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* loaded from: classes62.dex */
final class zzbb {
    static final BillingResult a;
    static final BillingResult b;
    static final BillingResult c;
    static final BillingResult d;
    static final BillingResult e;
    static final BillingResult f;
    static final BillingResult g;
    static final BillingResult h;
    static final BillingResult i;
    static final BillingResult j;
    static final BillingResult k;
    static final BillingResult l;
    static final BillingResult m;
    static final BillingResult n;
    static final BillingResult o;
    static final BillingResult p;
    static final BillingResult q;
    static final BillingResult r;
    static final BillingResult s;
    static final BillingResult t;
    static final BillingResult u;
    static final BillingResult v;
    static final BillingResult w;
    static final BillingResult x;
    static final BillingResult y;

    static {
        BillingResult.Builder b2 = BillingResult.b();
        b2.a(3);
        b2.a("Google Play In-app Billing API version is less than 3");
        a = b2.a();
        BillingResult.Builder b3 = BillingResult.b();
        b3.a(3);
        b3.a("Google Play In-app Billing API version is less than 9");
        b = b3.a();
        BillingResult.Builder b4 = BillingResult.b();
        b4.a(3);
        b4.a("Billing service unavailable on device.");
        c = b4.a();
        BillingResult.Builder b5 = BillingResult.b();
        b5.a(5);
        b5.a("Client is already in the process of connecting to billing service.");
        d = b5.a();
        BillingResult.Builder b6 = BillingResult.b();
        b6.a(5);
        b6.a("The list of SKUs can't be empty.");
        e = b6.a();
        BillingResult.Builder b7 = BillingResult.b();
        b7.a(5);
        b7.a("SKU type can't be empty.");
        f = b7.a();
        BillingResult.Builder b8 = BillingResult.b();
        b8.a(5);
        b8.a("Product type can't be empty.");
        g = b8.a();
        BillingResult.Builder b9 = BillingResult.b();
        b9.a(-2);
        b9.a("Client does not support extra params.");
        h = b9.a();
        BillingResult.Builder b10 = BillingResult.b();
        b10.a(5);
        b10.a("Invalid purchase token.");
        i = b10.a();
        BillingResult.Builder b11 = BillingResult.b();
        b11.a(6);
        b11.a("An internal error occurred.");
        j = b11.a();
        BillingResult.Builder b12 = BillingResult.b();
        b12.a(5);
        b12.a("SKU can't be null.");
        k = b12.a();
        BillingResult.Builder b13 = BillingResult.b();
        b13.a(0);
        l = b13.a();
        BillingResult.Builder b14 = BillingResult.b();
        b14.a(-1);
        b14.a("Service connection is disconnected.");
        m = b14.a();
        BillingResult.Builder b15 = BillingResult.b();
        b15.a(-3);
        b15.a("Timeout communicating with service.");
        n = b15.a();
        BillingResult.Builder b16 = BillingResult.b();
        b16.a(-2);
        b16.a("Client does not support subscriptions.");
        o = b16.a();
        BillingResult.Builder b17 = BillingResult.b();
        b17.a(-2);
        b17.a("Client does not support subscriptions update.");
        p = b17.a();
        BillingResult.Builder b18 = BillingResult.b();
        b18.a(-2);
        b18.a("Client does not support get purchase history.");
        q = b18.a();
        BillingResult.Builder b19 = BillingResult.b();
        b19.a(-2);
        b19.a("Client does not support price change confirmation.");
        r = b19.a();
        BillingResult.Builder b20 = BillingResult.b();
        b20.a(-2);
        b20.a("Play Store version installed does not support cross selling products.");
        s = b20.a();
        BillingResult.Builder b21 = BillingResult.b();
        b21.a(-2);
        b21.a("Client does not support multi-item purchases.");
        t = b21.a();
        BillingResult.Builder b22 = BillingResult.b();
        b22.a(-2);
        b22.a("Client does not support offer_id_token.");
        u = b22.a();
        BillingResult.Builder b23 = BillingResult.b();
        b23.a(-2);
        b23.a("Client does not support ProductDetails.");
        v = b23.a();
        BillingResult.Builder b24 = BillingResult.b();
        b24.a(-2);
        b24.a("Client does not support in-app messages.");
        w = b24.a();
        BillingResult.Builder b25 = BillingResult.b();
        b25.a(-2);
        b25.a("Client does not support alternative billing.");
        x = b25.a();
        BillingResult.Builder b26 = BillingResult.b();
        b26.a(5);
        b26.a("Unknown feature");
        y = b26.a();
    }
}
